name: Manual CI

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - unit
        - integration

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [1, 2, 3]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run build --if-present
    - name: Run tests
      run: |
        if [ "${{ github.event.inputs.test_type }}" = "unit" ]; then
          npm run test:unit -- --shard=${{ matrix.worker }}/3
        elif [ "${{ github.event.inputs.test_type }}" = "integration" ]; then
          npm run test:integration -- --shard=${{ matrix.worker }}/3
        else
          npm test -- --shard=${{ matrix.worker }}/3
        fi
